version: '3.8'

services:
    app:
        build: .
        container_name: gin-user-tasks
        ports :
            - 8080:8080
        networks:
            - datasource
        restart: on-failure
        env_file: .env
    mysql:
        image: mysql:5.7
        restart: always
        container_name: mysqldb
        ports:
            - 3306:3306
        networks:
            - datasource
        env_file: .env
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - my-db:/var/lib/mysql
networks:
  datasource:
      driver: bridge
volumes:
  my-db: